### ISSUE TITLE
about data_processing

### ISSUE THREAD

**Issue by mhyeonsoo** [mukund-ks/DeepLabV3-Segmentation#6]
Hi, thanks for the great sources.

I ran the training script, and saw that the process generated a new dataset in 'new_data' directory.
But when it starts training, it seems like it does not actually use the augmented data.

There are two issues.
1. data_processing does not generate the same amount of images as original data (much less)
2. data_processed images do not look like be used during training, it returns the error
```
tensorflow.python.framework.errors_impl.InvalidArgumentError: {{function_node __wrapped__IteratorGetNext_output_types_2_device_/job:localhost/replica:0/task:0/device:CPU:0}} Incompatible shapes at component 0: expected [?,256,256,3] but got [4,480,640,3].
```

**Comment by mukund-ks** [comment]
Hi, you can check the linked PR for a fix related to this.
